services:
  - type: web
    name: socal-business-intelligence-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: MAPBOX_ACCESS_TOKEN
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /health

