[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements-railway.txt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python run.py"
